In [1]:
import pickle
import numpy as np
import pandas as pd
import os
import warnings
warnings.filterwarnings('ignore')
import matplotlib.pyplot as plt
import tensorflow as tf

Using TensorFlow backend.


In [2]:
with open('X_train_scaled_dic.pickle', 'rb') as f:
    X_train_scaled_dic = pickle.load(f)
with open('X_test_scaled_dic.pickle', 'rb') as f:
    X_test_scaled_dic = pickle.load(f)
with open('y_train_dic.pickle', 'rb') as f:
    y_train_dic= pickle.load(f)
with open('y_test_dic.pickle', 'rb') as f:
    y_test_dic= pickle.load(f)

In [3]:
with open('sector.pickle', 'rb') as f:
    sector = pickle.load(f)

# 윈도우 데이터 셋 생성

In [6]:
# 윈도우 데이터셋 생성 함수
def windowed_dataset(X, y, X_size, y_size, X_shift, y_shift, X_stride, y_stride, batch_size):
    
    # numpy array x(input)를 Dataset으로 변환
    ds_x = tf.data.Dataset.from_tensor_slices(X)
    
    #윈도우셋 구성
    ds_x = ds_x.window(size=X_size,stride=X_stride, shift=X_shift, drop_remainder=True)
    #한 차원 줄야사 반환
    ds_x = ds_x.flat_map(lambda x: x.batch(X_size))
    
    ds_y = tf.data.Dataset.from_tensor_slices(y)
    
    #같은 인덱스에 있는 애들 끼리 묶기
    ds = tf.data.Dataset.zip((ds_x, ds_y))

    
    return ds.batch(batch_size).prefetch(1)

In [7]:
## 파라미터 지정

In [8]:
#윈도우 사이즈
WINDOW_SIZE = 10
# X에 대한 윈도우 함수 설정값
X_size = WINDOW_SIZE
X_shift = 1
X_stride = 1
# y에 대한 윈도우 함수 설정값
y_size = 1
y_shift = 1
y_stride = 1

batch_size = 32

In [9]:
tf_dataset_train_dic={}
for sector_name, sector_df in X_train_scaled_dic.items():
    tf_dataset_train_dic[sector_name] = {}
    for stock_code, df in sector_df.items():
        X_train = df
        y_train = y_train_dic[sector_name][stock_code]
        tf_dataset_train_dic[sector_name][stock_code] = windowed_dataset(X_train,y_train[WINDOW_SIZE:], X_size, y_size,
                                    X_shift, y_shift, X_stride, y_stride, batch_size)

        
        
tf_dataset_test_dic={}
for sector_name, sector_df in X_test_scaled_dic.items():
    tf_dataset_test_dic[sector_name] = {}
    for stock_code, df in sector_df.items():
        X_test = df
        y_test = y_test_dic[sector_name][stock_code]
        tf_dataset_test_dic[sector_name][stock_code] = windowed_dataset(X_test,y_test[WINDOW_SIZE:], X_size, y_size,
                                    X_shift, y_shift, X_stride, y_stride, batch_size)

In [10]:
# 데이터 shape, 미리보기로 체크
for x, y in tf_dataset_train_dic['Food']['097950'].take(1):
    print('X:', x.shape)
    print(x[:3])
    print()
    print('Y:', y.shape)
    print(y[:3])
    print('-'*100)

X: (32, 10, 5)
tf.Tensor(
[[[0.08718198 0.09461967 0.08545455 0.08431373 0.08082707]
  [0.04791903 0.08163265 0.07818182 0.08627451 0.08458647]
  [0.05072111 0.08534323 0.08727273 0.08823529 0.09586466]
  [0.12175059 0.1038961  0.09636364 0.10392157 0.10338346]
  [0.09202992 0.10760668 0.10545455 0.11568627 0.11466165]
  [0.09526414 0.12244898 0.12181818 0.1254902  0.11654135]
  [0.07396998 0.11131725 0.11636364 0.11764706 0.12030075]
  [0.06126101 0.11131725 0.11272727 0.10588235 0.10526316]
  [0.07603778 0.11502783 0.10363636 0.09803922 0.10714286]
  [0.15095811 0.10760668 0.12909091 0.10588235 0.14097744]]

 [[0.04791903 0.08163265 0.07818182 0.08627451 0.08458647]
  [0.05072111 0.08534323 0.08727273 0.08823529 0.09586466]
  [0.12175059 0.1038961  0.09636364 0.10392157 0.10338346]
  [0.09202992 0.10760668 0.10545455 0.11568627 0.11466165]
  [0.09526414 0.12244898 0.12181818 0.1254902  0.11654135]
  [0.07396998 0.11131725 0.11636364 0.11764706 0.12030075]
  [0.06126101 0.11131725 0.1

In [11]:
X_train_scaled_dic['Food']['097950'].iloc[:30]

거래량        시가        고가        저가        종가
일자                                                          
2010-06-22  0.087182  0.094620  0.085455  0.084314  0.080827
2010-06-23  0.047919  0.081633  0.078182  0.086275  0.084586
2010-06-24  0.050721  0.085343  0.087273  0.088235  0.095865
2010-06-25  0.121751  0.103896  0.096364  0.103922  0.103383
2010-06-28  0.092030  0.107607  0.105455  0.115686  0.114662
2010-06-29  0.095264  0.122449  0.121818  0.125490  0.116541
2010-06-30  0.073970  0.111317  0.116364  0.117647  0.120301
2010-07-01  0.061261  0.111317  0.112727  0.105882  0.105263
2010-07-02  0.076038  0.115028  0.103636  0.098039  0.107143
2010-07-05  0.150958  0.107607  0.129091  0.105882  0.140977
2010-07-06  0.389097  0.135436  0.183636  0.143137  0.186090
2010-07-07  0.249067  0.205937  0.205455  0.200000  0.197368
2010-07-08  0.140322  0.200371  0.203636  0.205882  0.214286
2010-07-09  0.095475  0.207792  0.198182  0.201961  0.204887
2010-07-12  0.101915  0.198516  0.190909  0.200000  0.191729
2010-07-13  0.262744  0.192950  0.214545  0.207843  0.219925
2010-07-14  0.084407  0.230056  0.223636  0.227451  0.229323
2010-07-15  0.065385  0.220779  0.218182  0.219608  0.227444
2010-07-16  0.063079  0.217069  0.221818  0.225490  0.219925
2010-07-19  0.028897  0.220779  0.207273  0.213725  0.199248
2010-07-20  0.079758  0.191095  0.192727  0.194118  0.191729
2010-07-21  0.083224  0.192950  0.220000  0.207843  0.231203
2010-07-22  0.180000  0.230056  0.249091  0.239216  0.251880
2010-07-23  0.121779  0.241187  0.240000  0.241176  0.234962
2010-07-26  0.061710  0.231911  0.218182  0.223529  0.208647
2010-07-27  0.078713  0.215213  0.203636  0.207843  0.216165
2010-07-28  0.062976  0.209647  0.212727  0.213725  0.227444
2010-07-29  0.058089  0.217069  0.221818  0.227451  0.234962
2010-07-30  0.573048  0.196660  0.194545  0.156863  0.165414
2010-08-02  0.325263  0.170686  0.158182  0.150980  0.146617

In [13]:
y_train_dic['Food']['097950'].iloc[[10,11,12]]

상향  하향  횡보
일자                    
2010-07-06   0   1   0
2010-07-07   0   1   0
2010-07-08   1   0   0

In [14]:
for sector_name, sector_tf in tf_dataset_train_dic.items():
    for stock_code, tf_dataset in sector_tf.items():
        for data in tf_dataset.take(1):
            print(stock_code)
            print(f'데이터셋(X) 구성(batch_size, window_size, feature갯수): {data[0].shape}')
            print(f'데이터셋(Y) 구성(batch_size, window_size, feature갯수): {data[1].shape}')

097950
데이터셋(X) 구성(batch_size, window_size, feature갯수): (32, 10, 5)
데이터셋(Y) 구성(batch_size, window_size, feature갯수): (32, 3)
271560
데이터셋(X) 구성(batch_size, window_size, feature갯수): (32, 10, 5)
데이터셋(Y) 구성(batch_size, window_size, feature갯수): (32, 3)
000080
데이터셋(X) 구성(batch_size, window_size, feature갯수): (32, 10, 5)
데이터셋(Y) 구성(batch_size, window_size, feature갯수): (32, 3)
004370
데이터셋(X) 구성(batch_size, window_size, feature갯수): (32, 10, 5)
데이터셋(Y) 구성(batch_size, window_size, feature갯수): (32, 3)
005300
데이터셋(X) 구성(batch_size, window_size, feature갯수): (32, 10, 5)
데이터셋(Y) 구성(batch_size, window_size, feature갯수): (32, 3)
093050
데이터셋(X) 구성(batch_size, window_size, feature갯수): (32, 10, 5)
데이터셋(Y) 구성(batch_size, window_size, feature갯수): (32, 3)
020000
데이터셋(X) 구성(batch_size, window_size, feature갯수): (32, 10, 5)
데이터셋(Y) 구성(batch_size, window_size, feature갯수): (32, 3)
105630
데이터셋(X) 구성(batch_size, window_size, feature갯수): (32, 10, 5)
데이터셋(Y) 구성(batch_size, window_size, feature갯수): (32, 3)
001070
데이터셋(X) 구

009150
데이터셋(X) 구성(batch_size, window_size, feature갯수): (32, 10, 5)
데이터셋(Y) 구성(batch_size, window_size, feature갯수): (32, 3)


# 모델

In [15]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, LSTM, Conv1D, Lambda
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.callbacks import EarlyStopping, ModelCheckpoint
from tqdm import tqdm


In [16]:
model_dic ={}
for sector_name, stock_list in sector.items():
    model_dic[sector_name] = {}
    for stock_code in stock_list:
        model_dic[sector_name][stock_code] = Sequential([
            # 1차원 feature map 생성
            Conv1D(filters=32, kernel_size=5,
                   padding="causal",
                   activation="relu",
                   #feature의 개수 3개
                   input_shape=[WINDOW_SIZE, 5]),
            # LSTM
            LSTM(16, activation='tanh'),
            Dense(16, activation="relu"),
            Dense(3,activation='softmax'),
        ])

In [17]:
optimizer = Adam(0.0005)
for sector_name, sector_model_dic in model_dic.items():
    for model in sector_model_dic.values():
        model.compile(loss='categorical_crossentropy', optimizer=optimizer, metrics=['acc'])

In [18]:
# earlystopping은 10번 epoch통안 val_loss 개선이 없다면 학습을 멈춥니다.
earlystopping = EarlyStopping(monitor='val_loss', patience=10)

In [4]:
filename_dic={}
for sector_name,stock_list in sector.items():
    filename_dic[sector_name] = {}
    for stock_code in stock_list:
        filename_dic[sector_name][stock_code] = os.path.join('MC',sector_name, stock_code+'ckeckpointer.ckpt')
        
        
with open('filename_dic.pickle','wb') as f:
    pickle.dump(filename_dic,f)

In [20]:
filename_dic['Food']

{'097950': 'MC\\Food\\097950ckeckpointer.ckpt',
 '271560': 'MC\\Food\\271560ckeckpointer.ckpt',
 '000080': 'MC\\Food\\000080ckeckpointer.ckpt',
 '004370': 'MC\\Food\\004370ckeckpointer.ckpt',
 '005300': 'MC\\Food\\005300ckeckpointer.ckpt'}

In [29]:
#체크포인트를 저장    
mc_dic = {}
for sector_name, filename_sector_dic in filename_dic.items():
    mc_dic[sector_name] = {}
    for stock_code, filename in filename_sector_dic.items():
        mc_dic[sector_name][stock_code] = ModelCheckpoint(filename, 
                             save_weights_only=True, 
                             save_best_only=True, 
                             monitor='val_acc',
                             verbose=1)

In [32]:
history_dic={}
# 학습+저장
for sector_name, tf_dataset_dic in tf_dataset_train_dic.items():
    history_dic[sector_name] = {}
    for stock_code, train_data in tf_dataset_dic.items():
        mc = mc_dic[sector_name][stock_code]
        test_data = tf_dataset_test_dic[sector_name][stock_code]
        history = model_dic[sector_name][stock_code].fit(train_data, 
                            validation_data=(test_data), 
                            epochs=80, 
                            callbacks=[mc, earlystopping])
        history_dic[sector_name][stock_code] = history

Epoch 1/80
75/75 [==============================] - 1s 12ms/step - loss: 0.7756 - acc: 0.5256 - val_loss: 0.7977 - val_acc: 0.5323

Epoch 00001: val_acc did not improve from 0.55102
Epoch 2/80
75/75 [==============================] - 1s 11ms/step - loss: 0.7782 - acc: 0.5067 - val_loss: 0.7918 - val_acc: 0.5408

Epoch 00002: val_acc did not improve from 0.55102
Epoch 3/80
75/75 [==============================] - 1s 10ms/step - loss: 0.7764 - acc: 0.5256 - val_loss: 0.7906 - val_acc: 0.5425

Epoch 00003: val_acc did not improve from 0.55102
Epoch 4/80
75/75 [==============================] - 1s 11ms/step - loss: 0.7760 - acc: 0.5239 - val_loss: 0.7888 - val_acc: 0.5425

Epoch 00004: val_acc did not improve from 0.55102
Epoch 5/80
75/75 [==============================] - 1s 11ms/step - loss: 0.7763 - acc: 0.5273 - val_loss: 0.7851 - val_acc: 0.5442

Epoch 00005: val_acc did not improve from 0.55102
Epoch 6/80
75/75 [==============================] - 1s 11ms/step - loss: 0.7766 - acc: 0.5

75/75 [==============================] - 1s 11ms/step - loss: 0.8091 - acc: 0.5122 - val_loss: 0.7588 - val_acc: 0.5561

Epoch 00042: val_acc did not improve from 0.57313
Epoch 43/80
75/75 [==============================] - 1s 10ms/step - loss: 0.8090 - acc: 0.5130 - val_loss: 0.7588 - val_acc: 0.5544

Epoch 00043: val_acc did not improve from 0.57313
Epoch 44/80
75/75 [==============================] - 1s 10ms/step - loss: 0.8089 - acc: 0.5139 - val_loss: 0.7588 - val_acc: 0.5510

Epoch 00044: val_acc did not improve from 0.57313
Epoch 45/80
75/75 [==============================] - 1s 11ms/step - loss: 0.8089 - acc: 0.5147 - val_loss: 0.7588 - val_acc: 0.5527

Epoch 00045: val_acc did not improve from 0.57313
Epoch 46/80
75/75 [==============================] - 1s 10ms/step - loss: 0.8089 - acc: 0.5155 - val_loss: 0.7588 - val_acc: 0.5510

Epoch 00046: val_acc did not improve from 0.57313
Epoch 47/80
75/75 [==============================] - 1s 10ms/step - loss: 0.8088 - acc: 0.5164 - 


Epoch 00006: val_acc did not improve from 0.51701
Epoch 7/80
75/75 [==============================] - 1s 10ms/step - loss: 0.8657 - acc: 0.5151 - val_loss: 0.8984 - val_acc: 0.5119

Epoch 00007: val_acc did not improve from 0.51701
Epoch 8/80
75/75 [==============================] - 1s 9ms/step - loss: 0.8656 - acc: 0.5151 - val_loss: 0.8986 - val_acc: 0.5119

Epoch 00008: val_acc did not improve from 0.51701
Epoch 9/80
75/75 [==============================] - 1s 10ms/step - loss: 0.8656 - acc: 0.5155 - val_loss: 0.8987 - val_acc: 0.5119

Epoch 00009: val_acc did not improve from 0.51701
Epoch 10/80
75/75 [==============================] - 1s 10ms/step - loss: 0.8655 - acc: 0.5155 - val_loss: 0.8988 - val_acc: 0.5119

Epoch 00010: val_acc did not improve from 0.51701
Epoch 11/80
75/75 [==============================] - 1s 9ms/step - loss: 0.8654 - acc: 0.5155 - val_loss: 0.8989 - val_acc: 0.5136

Epoch 00011: val_acc did not improve from 0.51701
Epoch 1/80
75/75 [=====================


Epoch 00001: val_acc did not improve from 0.42177
Epoch 2/80
75/75 [==============================] - 1s 10ms/step - loss: 0.7943 - acc: 0.6381 - val_loss: 1.1184 - val_acc: 0.4218

Epoch 00002: val_acc did not improve from 0.42177
Epoch 3/80
75/75 [==============================] - 1s 10ms/step - loss: 0.7935 - acc: 0.6381 - val_loss: 1.1190 - val_acc: 0.4218

Epoch 00003: val_acc did not improve from 0.42177
Epoch 4/80
75/75 [==============================] - 1s 11ms/step - loss: 0.7928 - acc: 0.6381 - val_loss: 1.1195 - val_acc: 0.4218

Epoch 00004: val_acc did not improve from 0.42177
Epoch 5/80
75/75 [==============================] - 1s 10ms/step - loss: 0.7923 - acc: 0.6381 - val_loss: 1.1213 - val_acc: 0.4218

Epoch 00005: val_acc did not improve from 0.42177
Epoch 6/80
75/75 [==============================] - 1s 10ms/step - loss: 0.7918 - acc: 0.6381 - val_loss: 1.1223 - val_acc: 0.4218

Epoch 00006: val_acc did not improve from 0.42177
Epoch 7/80
75/75 [=====================

75/75 [==============================] - 1s 11ms/step - loss: 0.9076 - acc: 0.4656 - val_loss: 0.7567 - val_acc: 0.4796

Epoch 00001: val_acc did not improve from 0.49150
Epoch 2/80
75/75 [==============================] - 1s 10ms/step - loss: 0.9074 - acc: 0.4664 - val_loss: 0.7567 - val_acc: 0.4796

Epoch 00002: val_acc did not improve from 0.49150
Epoch 3/80
75/75 [==============================] - 1s 10ms/step - loss: 0.9072 - acc: 0.4677 - val_loss: 0.7567 - val_acc: 0.4796

Epoch 00003: val_acc did not improve from 0.49150
Epoch 4/80
75/75 [==============================] - 1s 10ms/step - loss: 0.9070 - acc: 0.4673 - val_loss: 0.7567 - val_acc: 0.4796

Epoch 00004: val_acc did not improve from 0.49150
Epoch 5/80
75/75 [==============================] - 1s 10ms/step - loss: 0.9069 - acc: 0.4673 - val_loss: 0.7567 - val_acc: 0.4796

Epoch 00005: val_acc did not improve from 0.49150
Epoch 6/80
75/75 [==============================] - 1s 10ms/step - loss: 0.9067 - acc: 0.4664 - val_l

75/75 [==============================] - 1s 10ms/step - loss: 1.0111 - acc: 0.4454 - val_loss: 0.9663 - val_acc: 0.4864

Epoch 00009: val_acc did not improve from 0.48639
Epoch 10/80
75/75 [==============================] - 1s 11ms/step - loss: 1.0111 - acc: 0.4458 - val_loss: 0.9664 - val_acc: 0.4864

Epoch 00010: val_acc did not improve from 0.48639
Epoch 11/80
75/75 [==============================] - 1s 9ms/step - loss: 1.0107 - acc: 0.4479 - val_loss: 0.9663 - val_acc: 0.4864

Epoch 00011: val_acc did not improve from 0.48639
Epoch 12/80
75/75 [==============================] - 1s 10ms/step - loss: 1.0104 - acc: 0.4488 - val_loss: 0.9662 - val_acc: 0.4864

Epoch 00012: val_acc did not improve from 0.48639
Epoch 13/80
75/75 [==============================] - 1s 10ms/step - loss: 1.0102 - acc: 0.4505 - val_loss: 0.9661 - val_acc: 0.4864

Epoch 00013: val_acc did not improve from 0.48639
Epoch 14/80
75/75 [==============================] - 1s 11ms/step - loss: 1.0099 - acc: 0.4509 - v

75/75 [==============================] - 1s 10ms/step - loss: 0.7525 - acc: 0.5361 - val_loss: 0.7867 - val_acc: 0.5527

Epoch 00006: val_acc did not improve from 0.56803
Epoch 7/80
75/75 [==============================] - 1s 10ms/step - loss: 0.7521 - acc: 0.5374 - val_loss: 0.7867 - val_acc: 0.5510

Epoch 00007: val_acc did not improve from 0.56803
Epoch 8/80
75/75 [==============================] - 1s 10ms/step - loss: 0.7523 - acc: 0.5365 - val_loss: 0.7867 - val_acc: 0.5510

Epoch 00008: val_acc did not improve from 0.56803
Epoch 9/80
75/75 [==============================] - 1s 10ms/step - loss: 0.7520 - acc: 0.5353 - val_loss: 0.7867 - val_acc: 0.5527

Epoch 00009: val_acc did not improve from 0.56803
Epoch 10/80
75/75 [==============================] - 1s 11ms/step - loss: 0.7520 - acc: 0.5357 - val_loss: 0.7868 - val_acc: 0.5493

Epoch 00010: val_acc did not improve from 0.56803
Epoch 11/80
75/75 [==============================] - 1s 11ms/step - loss: 0.7515 - acc: 0.5382 - val

75/75 [==============================] - 1s 10ms/step - loss: 0.9870 - acc: 0.4824 - val_loss: 1.2333 - val_acc: 0.3980

Epoch 00006: val_acc did not improve from 0.46769
Epoch 7/80
75/75 [==============================] - 1s 10ms/step - loss: 0.9868 - acc: 0.4824 - val_loss: 1.2229 - val_acc: 0.4048

Epoch 00007: val_acc did not improve from 0.46769
Epoch 8/80
75/75 [==============================] - 1s 10ms/step - loss: 0.9867 - acc: 0.4824 - val_loss: 1.2150 - val_acc: 0.4133

Epoch 00008: val_acc did not improve from 0.46769
Epoch 9/80
75/75 [==============================] - 1s 10ms/step - loss: 0.9866 - acc: 0.4824 - val_loss: 1.2055 - val_acc: 0.4150

Epoch 00009: val_acc did not improve from 0.46769
Epoch 10/80
75/75 [==============================] - 1s 10ms/step - loss: 0.9865 - acc: 0.4832 - val_loss: 1.1969 - val_acc: 0.4167

Epoch 00010: val_acc did not improve from 0.46769
Epoch 11/80
75/75 [==============================] - 1s 10ms/step - loss: 0.9863 - acc: 0.4832 - val

75/75 [==============================] - 1s 10ms/step - loss: 0.9814 - acc: 0.4845 - val_loss: 1.0867 - val_acc: 0.4269

Epoch 00051: val_acc did not improve from 0.46769
Epoch 52/80
75/75 [==============================] - 1s 10ms/step - loss: 0.9813 - acc: 0.4840 - val_loss: 1.0863 - val_acc: 0.4303

Epoch 00052: val_acc did not improve from 0.46769
Epoch 53/80
75/75 [==============================] - 1s 10ms/step - loss: 0.9811 - acc: 0.4840 - val_loss: 1.0861 - val_acc: 0.4286

Epoch 00053: val_acc did not improve from 0.46769
Epoch 54/80
75/75 [==============================] - 1s 10ms/step - loss: 0.9810 - acc: 0.4840 - val_loss: 1.0859 - val_acc: 0.4269

Epoch 00054: val_acc did not improve from 0.46769
Epoch 55/80
75/75 [==============================] - 1s 10ms/step - loss: 0.9809 - acc: 0.4840 - val_loss: 1.0854 - val_acc: 0.4252

Epoch 00055: val_acc did not improve from 0.46769
Epoch 56/80
75/75 [==============================] - 1s 10ms/step - loss: 0.9807 - acc: 0.4845 - 

35/35 [==============================] - 0s 11ms/step - loss: 1.0310 - acc: 0.4438 - val_loss: 0.9692 - val_acc: 0.5428

Epoch 00014: val_acc did not improve from 0.56877
Epoch 15/80
35/35 [==============================] - 0s 11ms/step - loss: 1.0307 - acc: 0.4511 - val_loss: 0.9683 - val_acc: 0.5428

Epoch 00015: val_acc did not improve from 0.56877
Epoch 16/80
35/35 [==============================] - 0s 13ms/step - loss: 1.0312 - acc: 0.4493 - val_loss: 0.9651 - val_acc: 0.5465

Epoch 00016: val_acc did not improve from 0.56877
Epoch 17/80
35/35 [==============================] - 0s 10ms/step - loss: 1.0303 - acc: 0.4529 - val_loss: 0.9698 - val_acc: 0.5428

Epoch 00017: val_acc did not improve from 0.56877
Epoch 18/80
35/35 [==============================] - 0s 10ms/step - loss: 1.0310 - acc: 0.4484 - val_loss: 0.9682 - val_acc: 0.5465

Epoch 00018: val_acc did not improve from 0.56877
Epoch 19/80
35/35 [==============================] - 0s 10ms/step - loss: 1.0301 - acc: 0.4420 - 

47/47 [==============================] - 0s 10ms/step - loss: 1.0349 - acc: 0.4398 - val_loss: 0.8714 - val_acc: 0.4235

Epoch 00023: val_acc did not improve from 0.52459
Epoch 24/80
47/47 [==============================] - 0s 9ms/step - loss: 1.0344 - acc: 0.4378 - val_loss: 0.8708 - val_acc: 0.4235

Epoch 00024: val_acc did not improve from 0.52459
Epoch 25/80
47/47 [==============================] - 1s 11ms/step - loss: 1.0340 - acc: 0.4384 - val_loss: 0.8722 - val_acc: 0.4235

Epoch 00025: val_acc did not improve from 0.52459
Epoch 26/80
47/47 [==============================] - 0s 10ms/step - loss: 1.0337 - acc: 0.4344 - val_loss: 0.8709 - val_acc: 0.4235

Epoch 00026: val_acc did not improve from 0.52459
Epoch 27/80
47/47 [==============================] - 0s 10ms/step - loss: 1.0333 - acc: 0.4378 - val_loss: 0.8732 - val_acc: 0.4235

Epoch 00027: val_acc did not improve from 0.52459
Epoch 28/80
47/47 [==============================] - 0s 10ms/step - loss: 1.0329 - acc: 0.4351 - v

75/75 [==============================] - 1s 10ms/step - loss: 0.8389 - acc: 0.4715 - val_loss: 0.7689 - val_acc: 0.4609

Epoch 00012: val_acc did not improve from 0.53741
Epoch 1/80
75/75 [==============================] - 1s 12ms/step - loss: 0.9396 - acc: 0.4794 - val_loss: 0.8700 - val_acc: 0.5136

Epoch 00001: val_acc did not improve from 0.51871
Epoch 2/80
75/75 [==============================] - 1s 10ms/step - loss: 0.9395 - acc: 0.4790 - val_loss: 0.8698 - val_acc: 0.5136

Epoch 00002: val_acc did not improve from 0.51871
Epoch 3/80
75/75 [==============================] - 1s 10ms/step - loss: 0.9396 - acc: 0.4773 - val_loss: 0.8702 - val_acc: 0.5136

Epoch 00003: val_acc did not improve from 0.51871
Epoch 4/80
75/75 [==============================] - 1s 10ms/step - loss: 0.9394 - acc: 0.4790 - val_loss: 0.8702 - val_acc: 0.5136

Epoch 00004: val_acc did not improve from 0.51871
Epoch 5/80
75/75 [==============================] - 1s 9ms/step - loss: 0.9393 - acc: 0.4786 - val_lo

75/75 [==============================] - 1s 10ms/step - loss: 0.9463 - acc: 0.4786 - val_loss: 0.9948 - val_acc: 0.5170

Epoch 00033: val_acc did not improve from 0.53401
Epoch 34/80
75/75 [==============================] - 1s 9ms/step - loss: 0.9462 - acc: 0.4786 - val_loss: 0.9947 - val_acc: 0.5187

Epoch 00034: val_acc did not improve from 0.53401
Epoch 35/80
75/75 [==============================] - 1s 10ms/step - loss: 0.9462 - acc: 0.4773 - val_loss: 0.9947 - val_acc: 0.5255

Epoch 00035: val_acc did not improve from 0.53401
Epoch 36/80
75/75 [==============================] - 1s 10ms/step - loss: 0.9461 - acc: 0.4773 - val_loss: 0.9946 - val_acc: 0.5238

Epoch 00036: val_acc did not improve from 0.53401
Epoch 37/80
75/75 [==============================] - 1s 10ms/step - loss: 0.9461 - acc: 0.4777 - val_loss: 0.9945 - val_acc: 0.5238

Epoch 00037: val_acc did not improve from 0.53401
Epoch 38/80
75/75 [==============================] - 1s 10ms/step - loss: 0.9460 - acc: 0.4765 - v

75/75 [==============================] - 1s 10ms/step - loss: 0.9427 - acc: 0.4521 - val_loss: 0.9879 - val_acc: 0.4949

Epoch 00076: val_acc did not improve from 0.54592
Epoch 77/80
75/75 [==============================] - 1s 10ms/step - loss: 0.9426 - acc: 0.4526 - val_loss: 0.9880 - val_acc: 0.4932

Epoch 00077: val_acc did not improve from 0.54592
Epoch 78/80
75/75 [==============================] - 1s 10ms/step - loss: 0.9425 - acc: 0.4559 - val_loss: 0.9879 - val_acc: 0.4898

Epoch 00078: val_acc did not improve from 0.54592
Epoch 79/80
75/75 [==============================] - 1s 11ms/step - loss: 0.9423 - acc: 0.4563 - val_loss: 0.9879 - val_acc: 0.4898

Epoch 00079: val_acc did not improve from 0.54592
Epoch 80/80
75/75 [==============================] - 1s 10ms/step - loss: 0.9423 - acc: 0.4563 - val_loss: 0.9881 - val_acc: 0.4949

Epoch 00080: val_acc did not improve from 0.54592
Epoch 1/80
75/75 [==============================] - 1s 12ms/step - loss: 0.9588 - acc: 0.4647 - v

54/54 [==============================] - 1s 11ms/step - loss: 1.0142 - acc: 0.4273 - val_loss: 0.9570 - val_acc: 0.3671

Epoch 00006: val_acc did not improve from 0.53176
Epoch 7/80
54/54 [==============================] - 1s 12ms/step - loss: 1.0141 - acc: 0.4204 - val_loss: 0.9564 - val_acc: 0.3671

Epoch 00007: val_acc did not improve from 0.53176
Epoch 8/80
54/54 [==============================] - 1s 16ms/step - loss: 1.0139 - acc: 0.4111 - val_loss: 0.9562 - val_acc: 0.3671

Epoch 00008: val_acc did not improve from 0.53176
Epoch 9/80
54/54 [==============================] - 1s 18ms/step - loss: 1.0138 - acc: 0.4105 - val_loss: 0.9560 - val_acc: 0.3671

Epoch 00009: val_acc did not improve from 0.53176
Epoch 10/80
54/54 [==============================] - 1s 14ms/step - loss: 1.0137 - acc: 0.4123 - val_loss: 0.9558 - val_acc: 0.3388

Epoch 00010: val_acc did not improve from 0.53176
Epoch 11/80
54/54 [==============================] - 1s 15ms/step - loss: 1.0135 - acc: 0.4129 - val

75/75 [==============================] - 1s 10ms/step - loss: 0.6797 - acc: 0.7208 - val_loss: 0.8904 - val_acc: 0.6344

Epoch 00006: val_acc did not improve from 0.65476
Epoch 7/80
75/75 [==============================] - 1s 10ms/step - loss: 0.6795 - acc: 0.7208 - val_loss: 0.8894 - val_acc: 0.6344

Epoch 00007: val_acc did not improve from 0.65476
Epoch 8/80
75/75 [==============================] - 1s 9ms/step - loss: 0.6792 - acc: 0.7208 - val_loss: 0.8886 - val_acc: 0.6344

Epoch 00008: val_acc did not improve from 0.65476
Epoch 9/80
75/75 [==============================] - 1s 10ms/step - loss: 0.6790 - acc: 0.7208 - val_loss: 0.8877 - val_acc: 0.6344

Epoch 00009: val_acc did not improve from 0.65476
Epoch 10/80
75/75 [==============================] - 1s 10ms/step - loss: 0.6788 - acc: 0.7208 - val_loss: 0.8870 - val_acc: 0.6344

Epoch 00010: val_acc did not improve from 0.65476
Epoch 11/80
75/75 [==============================] - 1s 10ms/step - loss: 0.6785 - acc: 0.7208 - val_


Epoch 00050: val_acc did not improve from 0.65476
Epoch 51/80
75/75 [==============================] - 1s 12ms/step - loss: 0.6730 - acc: 0.7217 - val_loss: 0.8748 - val_acc: 0.6378

Epoch 00051: val_acc did not improve from 0.65476
Epoch 1/80
47/47 [==============================] - 1s 12ms/step - loss: 0.8590 - acc: 0.5182 - val_loss: 0.8738 - val_acc: 0.5647

Epoch 00001: val_acc improved from 0.55923 to 0.56474, saving model to MC\Distribution\028260ckeckpointer.ckpt
Epoch 2/80
47/47 [==============================] - 1s 11ms/step - loss: 0.8603 - acc: 0.5169 - val_loss: 0.8736 - val_acc: 0.5702

Epoch 00002: val_acc improved from 0.56474 to 0.57025, saving model to MC\Distribution\028260ckeckpointer.ckpt
Epoch 3/80
47/47 [==============================] - 1s 11ms/step - loss: 0.8602 - acc: 0.5169 - val_loss: 0.8736 - val_acc: 0.5675

Epoch 00003: val_acc did not improve from 0.57025
Epoch 4/80
47/47 [==============================] - 1s 15ms/step - loss: 0.8602 - acc: 0.5155 - va


Epoch 00030: val_acc did not improve from 0.55782
Epoch 31/80
75/75 [==============================] - 1s 12ms/step - loss: 0.8236 - acc: 0.5189 - val_loss: 0.8349 - val_acc: 0.5119

Epoch 00031: val_acc did not improve from 0.55782
Epoch 32/80
75/75 [==============================] - 1s 13ms/step - loss: 0.8235 - acc: 0.5181 - val_loss: 0.8349 - val_acc: 0.5102

Epoch 00032: val_acc did not improve from 0.55782
Epoch 1/80
75/75 [==============================] - 4s 21ms/step - loss: 1.0621 - acc: 0.3862 - val_loss: 1.1157 - val_acc: 0.3350

Epoch 00001: val_acc improved from -inf to 0.33503, saving model to MC\Power\015760ckeckpointer.ckpt
Epoch 2/80
75/75 [==============================] - 1s 12ms/step - loss: 1.0563 - acc: 0.3883 - val_loss: 1.1084 - val_acc: 0.3350

Epoch 00002: val_acc did not improve from 0.33503
Epoch 3/80
75/75 [==============================] - 1s 13ms/step - loss: 1.0536 - acc: 0.4173 - val_loss: 1.1059 - val_acc: 0.3350

Epoch 00003: val_acc did not improve

75/75 [==============================] - 1s 13ms/step - loss: 1.0020 - acc: 0.4471 - val_loss: 0.9367 - val_acc: 0.3946

Epoch 00009: val_acc did not improve from 0.42687
Epoch 10/80
75/75 [==============================] - 1s 11ms/step - loss: 1.0010 - acc: 0.4500 - val_loss: 0.9355 - val_acc: 0.4031

Epoch 00010: val_acc did not improve from 0.42687
Epoch 11/80
75/75 [==============================] - ETA: 0s - loss: 1.0003 - acc: 0.4468- ETA: 0s - loss: 0.9897 - acc: - 1s 10ms/step - loss: 1.0005 - acc: 0.4479 - val_loss: 0.9349 - val_acc: 0.4082

Epoch 00011: val_acc did not improve from 0.42687
Epoch 12/80
75/75 [==============================] - 1s 10ms/step - loss: 0.9999 - acc: 0.4492 - val_loss: 0.9350 - val_acc: 0.4303

Epoch 00012: val_acc improved from 0.42687 to 0.43027, saving model to MC\Power\017390ckeckpointer.ckpt
Epoch 13/80
75/75 [==============================] - 1s 11ms/step - loss: 0.9996 - acc: 0.4509 - val_loss: 0.9342 - val_acc: 0.4320

Epoch 00013: val_acc im

75/75 [==============================] - 1s 11ms/step - loss: 0.8317 - acc: 0.4908 - val_loss: 0.8355 - val_acc: 0.5119

Epoch 00008: val_acc did not improve from 0.51190
Epoch 9/80
75/75 [==============================] - 1s 11ms/step - loss: 0.8315 - acc: 0.4882 - val_loss: 0.8346 - val_acc: 0.5119

Epoch 00009: val_acc did not improve from 0.51190
Epoch 10/80
75/75 [==============================] - 1s 11ms/step - loss: 0.8313 - acc: 0.4912 - val_loss: 0.8341 - val_acc: 0.5119

Epoch 00010: val_acc did not improve from 0.51190
Epoch 11/80
75/75 [==============================] - 1s 10ms/step - loss: 0.8312 - acc: 0.4891 - val_loss: 0.8340 - val_acc: 0.5119

Epoch 00011: val_acc did not improve from 0.51190
Epoch 12/80
75/75 [==============================] - 1s 11ms/step - loss: 0.8310 - acc: 0.4929 - val_loss: 0.8341 - val_acc: 0.5119

Epoch 00012: val_acc did not improve from 0.51190
Epoch 13/80
75/75 [==============================] - 1s 11ms/step - loss: 0.8308 - acc: 0.4945 - v

75/75 [==============================] - 1s 12ms/step - loss: 0.2897 - acc: 0.9244 - val_loss: 0.4159 - val_acc: 0.8861

Epoch 00010: val_acc did not improve from 0.88605
Epoch 11/80
75/75 [==============================] - 1s 16ms/step - loss: 0.2886 - acc: 0.9244 - val_loss: 0.4149 - val_acc: 0.8861

Epoch 00011: val_acc did not improve from 0.88605
Epoch 12/80
75/75 [==============================] - 1s 13ms/step - loss: 0.2877 - acc: 0.9244 - val_loss: 0.4143 - val_acc: 0.8861

Epoch 00012: val_acc did not improve from 0.88605
Epoch 13/80
75/75 [==============================] - 1s 12ms/step - loss: 0.2869 - acc: 0.9244 - val_loss: 0.4135 - val_acc: 0.8861

Epoch 00013: val_acc did not improve from 0.88605
Epoch 14/80
75/75 [==============================] - 1s 13ms/step - loss: 0.2863 - acc: 0.9244 - val_loss: 0.4128 - val_acc: 0.8861

Epoch 00014: val_acc did not improve from 0.88605
Epoch 15/80
75/75 [==============================] - 1s 11ms/step - loss: 0.2858 - acc: 0.9244 - 

75/75 [==============================] - 1s 10ms/step - loss: 0.2781 - acc: 0.9244 - val_loss: 0.4002 - val_acc: 0.8861

Epoch 00055: val_acc did not improve from 0.88605
Epoch 56/80
75/75 [==============================] - 1s 10ms/step - loss: 0.2780 - acc: 0.9244 - val_loss: 0.3999 - val_acc: 0.8861

Epoch 00056: val_acc did not improve from 0.88605
Epoch 57/80
75/75 [==============================] - 1s 10ms/step - loss: 0.2779 - acc: 0.9244 - val_loss: 0.3998 - val_acc: 0.8861

Epoch 00057: val_acc did not improve from 0.88605
Epoch 58/80
75/75 [==============================] - 1s 10ms/step - loss: 0.2778 - acc: 0.9244 - val_loss: 0.3997 - val_acc: 0.8861

Epoch 00058: val_acc did not improve from 0.88605
Epoch 59/80
75/75 [==============================] - 1s 10ms/step - loss: 0.2772 - acc: 0.9244 - val_loss: 0.3989 - val_acc: 0.8861

Epoch 00059: val_acc did not improve from 0.88605
Epoch 60/80
75/75 [==============================] - 1s 11ms/step - loss: 0.2788 - acc: 0.9244 - 


Epoch 00006: val_acc did not improve from 0.43878
Epoch 7/80
75/75 [==============================] - 1s 11ms/step - loss: 0.9543 - acc: 0.4773 - val_loss: 0.9943 - val_acc: 0.4337

Epoch 00007: val_acc did not improve from 0.43878
Epoch 8/80
75/75 [==============================] - 1s 11ms/step - loss: 0.9541 - acc: 0.4773 - val_loss: 0.9937 - val_acc: 0.4337

Epoch 00008: val_acc did not improve from 0.43878
Epoch 9/80
75/75 [==============================] - 1s 11ms/step - loss: 0.9538 - acc: 0.4773 - val_loss: 0.9941 - val_acc: 0.4337

Epoch 00009: val_acc did not improve from 0.43878
Epoch 10/80
75/75 [==============================] - 1s 9ms/step - loss: 0.9540 - acc: 0.4773 - val_loss: 0.9934 - val_acc: 0.4337

Epoch 00010: val_acc did not improve from 0.43878
Epoch 11/80
75/75 [==============================] - 1s 11ms/step - loss: 0.9534 - acc: 0.4773 - val_loss: 0.9938 - val_acc: 0.4337

Epoch 00011: val_acc did not improve from 0.43878
Epoch 12/80
75/75 [===================

75/75 [==============================] - 1s 10ms/step - loss: 0.9524 - acc: 0.4547 - val_loss: 0.9622 - val_acc: 0.5204

Epoch 00066: val_acc did not improve from 0.52551
Epoch 67/80
75/75 [==============================] - 1s 10ms/step - loss: 0.9523 - acc: 0.4547 - val_loss: 0.9621 - val_acc: 0.5221

Epoch 00067: val_acc did not improve from 0.52551
Epoch 68/80
75/75 [==============================] - 1s 12ms/step - loss: 0.9523 - acc: 0.4547 - val_loss: 0.9619 - val_acc: 0.5204

Epoch 00068: val_acc did not improve from 0.52551
Epoch 69/80
75/75 [==============================] - 1s 11ms/step - loss: 0.9523 - acc: 0.4538 - val_loss: 0.9623 - val_acc: 0.5204

Epoch 00069: val_acc did not improve from 0.52551
Epoch 70/80
75/75 [==============================] - 1s 12ms/step - loss: 0.9523 - acc: 0.4542 - val_loss: 0.9622 - val_acc: 0.5204

Epoch 00070: val_acc did not improve from 0.52551
Epoch 71/80
75/75 [==============================] - 1s 11ms/step - loss: 0.9522 - acc: 0.4538 - 


Epoch 00005: val_acc did not improve from 0.48810
Epoch 6/80
75/75 [==============================] - 1s 12ms/step - loss: 0.9001 - acc: 0.4710 - val_loss: 0.7930 - val_acc: 0.4796

Epoch 00006: val_acc did not improve from 0.48810
Epoch 7/80
75/75 [==============================] - 1s 12ms/step - loss: 0.8999 - acc: 0.4723 - val_loss: 0.7930 - val_acc: 0.4711

Epoch 00007: val_acc did not improve from 0.48810
Epoch 8/80
75/75 [==============================] - 1s 10ms/step - loss: 0.8997 - acc: 0.4719 - val_loss: 0.7933 - val_acc: 0.4728

Epoch 00008: val_acc did not improve from 0.48810
Epoch 9/80
75/75 [==============================] - 1s 10ms/step - loss: 0.8996 - acc: 0.4731 - val_loss: 0.7942 - val_acc: 0.4728

Epoch 00009: val_acc did not improve from 0.48810
Epoch 10/80
75/75 [==============================] - 1s 10ms/step - loss: 0.8994 - acc: 0.4765 - val_loss: 0.7945 - val_acc: 0.4728

Epoch 00010: val_acc did not improve from 0.48810
Epoch 11/80
75/75 [===================

75/75 [==============================] - 1s 9ms/step - loss: 0.7731 - acc: 0.5281 - val_loss: 0.7365 - val_acc: 0.4762

Epoch 00010: val_acc did not improve from 0.47619
Epoch 11/80
75/75 [==============================] - 1s 10ms/step - loss: 0.7730 - acc: 0.5281 - val_loss: 0.7366 - val_acc: 0.4762

Epoch 00011: val_acc did not improve from 0.47619
Epoch 12/80
75/75 [==============================] - 1s 9ms/step - loss: 0.7729 - acc: 0.5281 - val_loss: 0.7367 - val_acc: 0.4762

Epoch 00012: val_acc did not improve from 0.47619
Epoch 13/80
75/75 [==============================] - 1s 10ms/step - loss: 0.7728 - acc: 0.5281 - val_loss: 0.7368 - val_acc: 0.4762

Epoch 00013: val_acc did not improve from 0.47619
Epoch 14/80
75/75 [==============================] - 1s 10ms/step - loss: 0.7727 - acc: 0.5281 - val_loss: 0.7369 - val_acc: 0.4762

Epoch 00014: val_acc did not improve from 0.47619
Epoch 15/80
75/75 [==============================] - 1s 10ms/step - loss: 0.7727 - acc: 0.5281 - va

75/75 [==============================] - 1s 9ms/step - loss: 0.9997 - acc: 0.4496 - val_loss: 0.9265 - val_acc: 0.4694

Epoch 00005: val_acc did not improve from 0.47619
Epoch 6/80
75/75 [==============================] - 1s 9ms/step - loss: 0.9993 - acc: 0.4563 - val_loss: 0.9248 - val_acc: 0.4677

Epoch 00006: val_acc did not improve from 0.47619
Epoch 7/80
75/75 [==============================] - 1s 9ms/step - loss: 0.9986 - acc: 0.4576 - val_loss: 0.9237 - val_acc: 0.4660

Epoch 00007: val_acc did not improve from 0.47619
Epoch 8/80
75/75 [==============================] - 1s 10ms/step - loss: 0.9980 - acc: 0.4576 - val_loss: 0.9229 - val_acc: 0.4660

Epoch 00008: val_acc did not improve from 0.47619
Epoch 9/80
75/75 [==============================] - 1s 10ms/step - loss: 0.9977 - acc: 0.4555 - val_loss: 0.9222 - val_acc: 0.4677

Epoch 00009: val_acc did not improve from 0.47619
Epoch 10/80
75/75 [==============================] - 1s 10ms/step - loss: 0.9974 - acc: 0.4563 - val_los


Epoch 00014: val_acc did not improve from 0.57313
Epoch 15/80
75/75 [==============================] - 1s 10ms/step - loss: 0.7859 - acc: 0.5336 - val_loss: 0.7983 - val_acc: 0.5493

Epoch 00015: val_acc did not improve from 0.57313
Epoch 16/80
75/75 [==============================] - 1s 10ms/step - loss: 0.7858 - acc: 0.5348 - val_loss: 0.7980 - val_acc: 0.5493

Epoch 00016: val_acc did not improve from 0.57313
Epoch 17/80
75/75 [==============================] - 1s 9ms/step - loss: 0.7857 - acc: 0.5332 - val_loss: 0.7974 - val_acc: 0.5578

Epoch 00017: val_acc did not improve from 0.57313
Epoch 18/80
75/75 [==============================] - 1s 10ms/step - loss: 0.7857 - acc: 0.5336 - val_loss: 0.7971 - val_acc: 0.5561

Epoch 00018: val_acc did not improve from 0.57313
Epoch 19/80
75/75 [==============================] - 1s 10ms/step - loss: 0.7856 - acc: 0.5361 - val_loss: 0.7968 - val_acc: 0.5595

Epoch 00019: val_acc did not improve from 0.57313
Epoch 20/80
75/75 [================

75/75 [==============================] - 1s 10ms/step - loss: 0.9635 - acc: 0.4845 - val_loss: 1.0535 - val_acc: 0.4286

Epoch 00043: val_acc did not improve from 0.42857
Epoch 44/80
75/75 [==============================] - 1s 11ms/step - loss: 0.9635 - acc: 0.4836 - val_loss: 1.0536 - val_acc: 0.4286

Epoch 00044: val_acc did not improve from 0.42857
Epoch 45/80
75/75 [==============================] - 1s 11ms/step - loss: 0.9635 - acc: 0.4840 - val_loss: 1.0536 - val_acc: 0.4286

Epoch 00045: val_acc did not improve from 0.42857
Epoch 46/80
75/75 [==============================] - 1s 11ms/step - loss: 0.9634 - acc: 0.4840 - val_loss: 1.0536 - val_acc: 0.4286

Epoch 00046: val_acc did not improve from 0.42857
Epoch 47/80
75/75 [==============================] - 1s 11ms/step - loss: 0.9634 - acc: 0.4836 - val_loss: 1.0537 - val_acc: 0.4286

Epoch 00047: val_acc did not improve from 0.42857
Epoch 48/80
75/75 [==============================] - 1s 10ms/step - loss: 0.9634 - acc: 0.4845 - 

In [42]:
with open('label_ratio_dic.pickle', 'rb') as f:
    label_ratio_dic = pickle.load(f)

In [44]:
certificated_stock_dic = {}

for sector_name, sector_model in model_dic.items():
    certificated_stock_dic[sector_name] = []
    for stock_code, model in sector_model.items():
        s = model.evaluate(tf_dataset_test_dic[sector_name][stock_code])[1]
        if s>0.55:
            print(f'{stock_code}: 의 레이블 비율')
            print(np.around(label_ratio_dic[sector_name][stock_code]*100,2))
            print(f'{stock_code} : 의 정확도 : {np.round(s*100,2)}')
            certificated_stock_dic[sector_name].append(stock_code)
            

19/19 [==============================] - 0s 8ms/step - loss: 0.7777 - acc: 0.5527
097950: 의 레이블 비율
상향    49.03
하향    48.80
횡보     2.17
Name: Label, dtype: float64
097950 : 의 정확도 : 55.27
19/19 [==============================] - 0s 8ms/step - loss: 0.7905 - acc: 0.5561
090430: 의 레이블 비율
하향    48.66
상향    47.22
횡보     4.11
Name: Label, dtype: float64
090430 : 의 정확도 : 55.61
19/19 [==============================] - 0s 7ms/step - loss: 0.6392 - acc: 0.8248
003410: 의 레이블 비율
횡보    87.83
하향     6.89
상향     5.28
Name: Label, dtype: float64
003410 : 의 정확도 : 82.48
19/19 [==============================] - 0s 8ms/step - loss: 0.7874 - acc: 0.5544
010130: 의 레이블 비율
하향    50.43
상향    47.83
횡보     1.74
Name: Label, dtype: float64
010130 : 의 정확도 : 55.44
19/19 [==============================] - 0s 8ms/step - loss: 0.7820 - acc: 0.7092
047040: 의 레이블 비율
횡보    64.18
상향    18.60
하향    17.22
Name: Label, dtype: float64
047040 : 의 정확도 : 70.92
19/19 [==============================] - 0s 8ms/step - loss: 0.8748 - 

In [45]:
with open('certificated_stock_dic.pickle', 'wb') as f:
    pickle.dump(certificated_stock_dic,f)